"""
query_layer/config.py — centralised settings.

All values are read from environment variables (populated by python-dotenv
from the project-root .env file). Mandatory fields raise EnvironmentError on
startup if missing, so misconfiguration is caught immediately.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

_PROJECT_ROOT = Path(__file__).resolve().parent.parent


def _require(key: str) -> str:
    """Returns env var value or raises if unset."""
    value = os.getenv(key)
    if not value:
        raise OSError(
            f"Required environment variable '{key}' is missing. Check the .env file at {_PROJECT_ROOT / '.env'}."
        )
    return value


@dataclass(frozen=True)
class Settings:
    # ---------------------------------------------------------------------------
    # MinIO / S3
    # ---------------------------------------------------------------------------

    # e.g. "localhost:9000" (no scheme, no trailing slash)
    minio_endpoint: str = field(default_factory=lambda: os.getenv("MINIO_ENDPOINT"))
    minio_access_key: str = field(default_factory=lambda: _require("MINIO_ACCESS_KEY"))
    minio_secret_key: str = field(default_factory=lambda: _require("MINIO_SECRET_KEY"))

    # ---------------------------------------------------------------------------
    # DuckDB
    # ---------------------------------------------------------------------------

    # Path to the .duckdb catalog file consumed by Superset.
    # Generated by scripts/setup_duckdb_catalog.py; gitignored.
    catalog_path: Path = field(
        default_factory=lambda: Path(os.getenv("DUCKDB_CATALOG_PATH", str(_PROJECT_ROOT / "superset_views.duckdb")))
    )

    # DuckDB home directory.
    # DuckDB stores persistent secrets under {duckdb_home}/.duckdb/stored_secrets/.
    # This directory is mounted read-only into the Superset container so it can
    # auto-load the S3 credentials without any additional configuration.
    duckdb_home: Path = field(
        default_factory=lambda: Path(os.getenv("DUCKDB_HOME", str(_PROJECT_ROOT / "duckdb_data")))
    )

    # ---------------------------------------------------------------------------
    # Gold layer
    # ---------------------------------------------------------------------------

    # Base S3 path for all Gold Delta tables.
    # Must match the paths written by the elt_pipeline gold assets.
    gold_base_path: str = field(default_factory=lambda: os.getenv("GOLD_BASE_PATH", "s3://lakehouse/gold/amazon"))


# Module-level singleton — import this everywhere.
settings = Settings()
